import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar } from '@ionic/react';
import MovieReview from '../components/MovieReview';

const Movie: React.FC = () => {
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Noah's Movie Reviews</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <div id="movieBody">
          <div>
            <h2>Noah's Recent Reviews</h2>
          </div>
          <MovieReview ratingImgLink={"assets/media/5stars.jpg"} imgLink={"assets/media/godfather.jpg"} reviewContent={'Those who have read the novel may be surprised to find Michael at the center of the movie, instead of Don Corleone. In fact, this is simply an economical way for Coppola to get at the heart of the Puzo story, which dealt with the transfer of power within the family. Marlon Brando, who plays the Godfather as a shrewd, unbreakable old man, actually has the character lead in the movie; Al Pacino, with a brilliantly developed performance as Michael, is the lead. But Brando’s performance is a skillful throwaway, even though it earned him an Academy Award for best actor. His voice is wheezy and whispery, and his physical movements deliberately lack precision; the effect is of a man so accustomed to power that he no longer needs to remind others. Brando does look the part of old Don Corleone, mostly because of acting and partly because of the makeup, although he seems to have stuffed a little too much cotton into his jowls, making his lower face immobile.'}/>
          <MovieReview ratingImgLink={"assets/media/5stars.jpg"} imgLink={"assets/media/godfather.jpg"} reviewContent={'Those who have read the novel may be surprised to find Michael at the center of the movie, instead of Don Corleone. In fact, this is simply an economical way for Coppola to get at the heart of the Puzo story, which dealt with the transfer of power within the family. Marlon Brando, who plays the Godfather as a shrewd, unbreakable old man, actually has the character lead in the movie; Al Pacino, with a brilliantly developed performance as Michael, is the lead. But Brando’s performance is a skillful throwaway, even though it earned him an Academy Award for best actor. His voice is wheezy and whispery, and his physical movements deliberately lack precision; the effect is of a man so accustomed to power that he no longer needs to remind others. Brando does look the part of old Don Corleone, mostly because of acting and partly because of the makeup, although he seems to have stuffed a little too much cotton into his jowls, making his lower face immobile.'}/>
          <MovieReview ratingImgLink={"assets/media/5stars.jpg"} imgLink={"assets/media/godfather.jpg"} reviewContent={'Those who have read the novel may be surprised to find Michael at the center of the movie, instead of Don Corleone. In fact, this is simply an economical way for Coppola to get at the heart of the Puzo story, which dealt with the transfer of power within the family. Marlon Brando, who plays the Godfather as a shrewd, unbreakable old man, actually has the character lead in the movie; Al Pacino, with a brilliantly developed performance as Michael, is the lead. But Brando’s performance is a skillful throwaway, even though it earned him an Academy Award for best actor. His voice is wheezy and whispery, and his physical movements deliberately lack precision; the effect is of a man so accustomed to power that he no longer needs to remind others. Brando does look the part of old Don Corleone, mostly because of acting and partly because of the makeup, although he seems to have stuffed a little too much cotton into his jowls, making his lower face immobile.'}/>
          <MovieReview ratingImgLink={"assets/media/5stars.jpg"} imgLink={"assets/media/godfather.jpg"} reviewContent={'Those who have read the novel may be surprised to find Michael at the center of the movie, instead of Don Corleone. In fact, this is simply an economical way for Coppola to get at the heart of the Puzo story, which dealt with the transfer of power within the family. Marlon Brando, who plays the Godfather as a shrewd, unbreakable old man, actually has the character lead in the movie; Al Pacino, with a brilliantly developed performance as Michael, is the lead. But Brando’s performance is a skillful throwaway, even though it earned him an Academy Award for best actor. His voice is wheezy and whispery, and his physical movements deliberately lack precision; the effect is of a man so accustomed to power that he no longer needs to remind others. Brando does look the part of old Don Corleone, mostly because of acting and partly because of the makeup, although he seems to have stuffed a little too much cotton into his jowls, making his lower face immobile.'}/>
          <MovieReview ratingImgLink={"assets/media/5stars.jpg"} imgLink={"assets/media/godfather.jpg"} reviewContent={'Those who have read the novel may be surprised to find Michael at the center of the movie, instead of Don Corleone. In fact, this is simply an economical way for Coppola to get at the heart of the Puzo story, which dealt with the transfer of power within the family. Marlon Brando, who plays the Godfather as a shrewd, unbreakable old man, actually has the character lead in the movie; Al Pacino, with a brilliantly developed performance as Michael, is the lead. But Brando’s performance is a skillful throwaway, even though it earned him an Academy Award for best actor. His voice is wheezy and whispery, and his physical movements deliberately lack precision; the effect is of a man so accustomed to power that he no longer needs to remind others. Brando does look the part of old Don Corleone, mostly because of acting and partly because of the makeup, although he seems to have stuffed a little too much cotton into his jowls, making his lower face immobile.'}/>
          <MovieReview ratingImgLink={"assets/media/5stars.jpg"} imgLink={"assets/media/godfather.jpg"} reviewContent={'Those who have read the novel may be surprised to find Michael at the center of the movie, instead of Don Corleone. In fact, this is simply an economical way for Coppola to get at the heart of the Puzo story, which dealt with the transfer of power within the family. Marlon Brando, who plays the Godfather as a shrewd, unbreakable old man, actually has the character lead in the movie; Al Pacino, with a brilliantly developed performance as Michael, is the lead. But Brando’s performance is a skillful throwaway, even though it earned him an Academy Award for best actor. His voice is wheezy and whispery, and his physical movements deliberately lack precision; the effect is of a man so accustomed to power that he no longer needs to remind others. Brando does look the part of old Don Corleone, mostly because of acting and partly because of the makeup, although he seems to have stuffed a little too much cotton into his jowls, making his lower face immobile.'}/>
        </div>
      </IonContent>
    </IonPage>
  );
};

export default Movie;